#!/bin/bash
echo "Logan - start bash boot script"
#Updates
yum update -y
echo "Logan - yum updates and upgrades complete"
#instal apache
yum install httpd -y
echo "Logan - httpd installed"
yum install amazon-efs-utils -y
echo "Logan - installed amazone-efs-utils"
#start apache service
service httpd start
echo "Logan - started webserver"
#change directory
cd /var/www/html
echo "Logan - change directory cd /var/www/html"
#make index.html
echo "<html><body><h1>Hello AWS World</h1></body></html>" > index.html
echo "Logan - hello aws world created"
#copy files from s3
aws s3 cp s3://logansbucket . --recursive
echo "Logan - s3 bucket copied to root"
#start apache server on reboot
systemctl start httpd
systemctl enable httpd
echo "Logan - systemctl start and enable httpd on reboot"
