#!/bin/bash
echo "Logan - start bash boot script"
#Updates
yum update -y
echo "Logan - yum updates and upgrades complete"
#instal apache
yum install httpd -y
echo "Logan - httpd installed"
#start apache service
service httpd start
echo "Logan - started webserver"
#start apache server on reboot
systemctl start httpd
systemctl enable httpd
echo "Logan - systemctl start and enable httpd on reboot"
#change directory
cd /var/www/html
echo "Logan - change directory cd /var/www/html"
#set permissions
chown  ec2-user /var/www/html/*
chmod -R o+r /var/www/html/*
echo "Logan - permission set"
#make index.html
echo "<html><h1>Hello AWS World</h1></html>" > index.html
echo "Logan - hello aws world created"
#copy files from s3
aws s3 cp s3://logansbucket . --recursive
echo "Logan - s3 bucket copied to root"
#set permissions for directory
#chmod -R 755 /var/www/html/*
#echo "Logan - chmod -R 755 /var/www/html/*"
#Giving Apache write access to /var/www/html
#chown -R apache:apache /var/www/html/*
#echo "chown -R apache:apache /var/www/html/*"
#instal EFS (elastic file system)
yum install amazon-efs-utils -y
echo "Logan - installed amazone-efs-utils"
#set EFS id
file_system_id_1=fs-0ac3b23969db17224
echo "Logan - set efs id to" + $file_system_id_1
#set mount point directory
efs_mount_point_1=/var/www/html
echo "Logan - set efs mount point"
echo "mount point is " + $efs_mount_point_1
mkdir -p "${efs_mount_point_1}"
echo "made directory at " + $efs_mount_point_1
#mount directory
test -f "/sbin/mount.efs" && printf "\n${file_system_id_1}:/ ${efs_mount_point_1} efs iam,tls,_netdev\n" >> /etc/fstab || printf "\n${file_system_id_1}.efs.us-west-2.amazonaws.com:/ ${efs_mount_point_1} nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,_netdev 0 0\n" >> /etc/fstab
test -f "/sbin/mount.efs" && grep -ozP 'client-info]\nsource' '/etc/amazon/efs/efs-utils.conf'; if [[ $? == 1 ]]; then printf "\n[client-info]\nsource=liw\n" >> /etc/amazon/efs/efs-utils.conf; fi;
retryCnt=15; waitTime=30; while true; do mount -a -t efs,nfs4 defaults; if [ $? = 0 ] || [ $retryCnt -lt 1 ]; then echo File system mounted successfully; break; fi; echo File system not available, retrying to mount.; ((retryCnt--)); sleep $waitTime; done;
