#!/bin/bash
#don't know what this does
yum install amazon-linux-extras httpd -y 
amazon-linux-extras install php7.2 -y

#instal apache
yum install httpd -y
systemctl start httpd
systemctl enable httpd

#change directory to apache's html folder
cd /var/www/html
#download WP tar file
wget https://wordpress.org/latest.tar.gz
#unzip tar file
tar -xzf latest.tar.gz
#instal WP
cp -r wordpress/* /var/www/html/
#remove wordpress
rm -rf wordpress
#remove tar file
rm -rf latest.tar.gz

#don't know what this does
chmod -R 755 /var/www/html/*
chown -R apache:apache /var/www/html/*

#start apache service
service httpd start