#!/bin/bash
#don't know what this does

#instal apache
yum install amazon-linux-extras httpd -y
#instal php
amazon-linux-extras install php7.2 -y

#instal apache
yum install httpd -y
#start apache server
systemctl start httpd
systemctl enable httpd

#change directory to apache's html folder
cd /var/www/html
#download WP tar file
wget https://wordpress.org/latest.tar.gz
#unzip tar file
tar -xzf latest.tar.gz
#instal WP
cp -r wordpress/* /var/www/html/
#remove wordpress
rm -rf wordpress
#remove tar file
rm -rf latest.tar.gz

#set permissions for directory
chmod -R 755 /var/www/html/*
#Giving Apache write access to /var/www/html
chown -R apache:apache /var/www/html/*

#start apache service
service httpd start
