#!/bin/bash
#update security
yum update -y --security
# Install Apache Web Server, PHP, epel, and stress
yum install -y httpd mysql stress
amazon-linux-extras install -y php7.2 epel
# Download Lab files
wget https://aws-tc-largeobjects.s3.us-west-2.amazonaws.com/CUR-TF-100-TULABS-1/55-lab-creating-ha-apps/s3/inventory-app.zip
wget http://aws-tc-largeobjects.s3.amazonaws.com/CUR-TF-100-TULABS-1/10-lab-autoscaling-linux/s3/ec2-stress.zip
unzip inventory-app.zip -d /var/www/html/
# Download and install the AWS SDK for PHP
wget https://github.com/aws/aws-sdk-php/releases/download/3.62.3/aws.zip
unzip aws -d /var/www/html
# Turn on web server
chkconfig httpd on
service httpd start
# redundant? start web server
systemctl enable httpd.service
systemctl start httpd